### ISSUE TITLE
Attitude control

### ISSUE THREAD

**Issue by timothy** [nasa/cFS#124]
I am looking for the Attitude Control System or GN&C. Is there any documentation that can point me to where the code is?

**Comment by skliper** [comment]
Projects typically write custom ACS/GN&C apps so we don't have a general open source solution, but there's resources available that make it easier.  https://github.com/nasa/SIL is the simulink interface layer, which makes it easier to integrate simulink autocode to CFS, or if you've got custom c code see https://github.com/nasa/ECI.

**Comment by astrogeco** [comment]
Another resource we use at NASA-GSFC is the [42 spacecraft simulator](https://github.com/ericstoneking/42). Good luck!
