### ISSUE TITLE
Contributor License Agreement Template

### ISSUE THREAD

**Issue by jlucas9** [nasa/cFS#15]
**Describe the bug**
Unable to quickly find the Contributor License Agreement (CLA). Recommend adding to README of each repository.

**Reporter Info**
John P. Lucas - NASA GSFC

**Comment by skliper** [comment]
They are now linked from the pull request template (see https://github.com/nasa/cFE/blob/master/.github/pull_request_template.md for example) and located in the cFE docs and OSAL doc directory.  Links will be added soon to the CONTRIBUTING guide in each repo.
