### ISSUE TITLE
Create Contributing.md

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/cFS#194]
**Is your feature request related to a problem? Please describe.**
Create a Contributing.md file so users know how to engage with cFS. 

**Describe the solution you'd like**
Include instructions on how to report bugs, request a feature, participate in discussions, create pull requests, and view security vulnerabilities. 

**Additional context**
I would like to create a code of conduct for this file. I would also like to explore how cFS could allow more discussions from the community such as using gitter.im, discourse, or a discussions template to use in issues.

**Requester Info**
Ariel Adams, ASRC Federal

**Comment by skliper** [comment]
Good plan!  There was a draft started as a PR in cFE (I think), and I've sent Gerardo a few things on the PR submission process (and I think he's collected quite a bit of other info).  All good stuff to actually formalize and provide to users.  Could like to it from the submodules (vs writing one for every repo).

**Comment by ArielSAdamsNASA** [comment]
@skliper I used the draft from cFE that you mentioned for the cFS contributing.md file, but there are some things missing and topics I would like to add. It would be great to get your feedback! Here is the [PR](https://github.com/nasa/cFS/pull/195)
