### ISSUE TITLE
Complete Writing High Quality Code for Contributing.MD

### ISSUE THREAD

**Issue by ArielSAdamsNASA** [nasa/cFS#208]
**Is your feature request related to a problem? Please describe.**
Provide instructions to users on how to write high quality code. 

**Describe the solution you'd like**
Complete the Writing High Quality Code section to add to the Contributing Guide. 

**Additional context**
The draft so far:

## Writing High-Quality Code

1. Follow cFS code conventions (formatting, symbol naming, file naming, etc) but do *not* change/reformat existing code except to address your changes.

2. For any new API's, add unit tests to cover nominal and off-nominal conditions.

3. Add/edit stubs to the unit test codebase for any new/modified functions.

4. For any changes to existing API's, alter the unit tests to cover the changes (and remove tests made irrelevant due to your changes).

5. Test your code, on a Linux platform (at minimum) --
    _TODO:_ Specific distros/versions/CPU architectures of Linux?

6. Build your code, including unit tests.
    _TODO:_ need "standard" build process.

6. Run the unit tests (all passed, yes?)
    _TODO:_ need "standard" test procedure.

7. Run the main cfs executable (no errors reported, yes?)
    _TODO:_ need "standard" test procedure, including targets.cmake recommendations.

8. ?? Do we expect contributors to run coverage ?? Guessing no.

**Requester Info**
Ariel Adams, ASRC Federal

**Comment by skliper** [comment]
One option for 5-9 is to simply provide instructions for how to trigger all the GitHub actions that perform all these activities for the user.  Could also reference the implementations of those actions from the documentation for the definitive/working instructions vs duplicating the instructions in documentation which could get out of sync.  It's even easier if the actions are set to run on all pushes, then a user can simply push a bundle branch to their fork and see that everything passes (or not).

**Comment by ArielSAdamsNASA** [comment]
> One option for 5-9 is to simply provide instructions for how to trigger all the GitHub actions that perform all these activities for the user. 

I personally prefer this option.
