### ISSUE TITLE
Syntax for Table Dump Command

### ISSUE THREAD

**Issue by JimKaidyNASA** [nasa/cFS#21]
When attempting to dump a table the format for the python GroundSystem is unclear.

![image](https://user-images.githubusercontent.com/52501916/67683286-7f0cbe00-f967-11e9-8bb2-ffa3bb4df303.png)

My attempt syntax is as follows.  It appears to concatenate the table and the table file name, making it hard to discern any proper convention for the arguments of the command.

![image](https://user-images.githubusercontent.com/52501916/67683398-b9765b00-f967-11e9-8cc1-3b2475a0db8e.png)

**Comment by astrogeco** [comment]
@JimKaidyNASA not sure if you've figured this out but for future questions use the mailing list 
https://lists.nasa.gov/mailman/listinfo/cfs-community

**Comment by avan989** [comment]
@JimKaidyNASA This is a little late but check your parameter file for the dump command. Your length definition for the tableName is off, that is probably why it is getting concatenate like that. I recommend just redoing the entire "table" command for the Ground System, your length for the DumpFileName is probably off too. 

Reference Guide-GroundSystem.txt for instructions on how to generate command. Hope this help.
