### ISSUE TITLE
Add links or instructions to pull request squash and ammend section

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFS#226]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
```.md
Once a Pull Request Ready for Review

    Verify the commit message and PR title use the template Fix #XYZ, SHORT_DESCRIPTION.
    Verify there is only one commit message. Squash or amend the commit messages if necessary.
    Verify that the PR passes all checks.
    The project team will label the issue and evaluate the pull request in the weekly configuration control board (CCB) meeting. For more information, visit The cFS CCB Process.
    If the pull request is accepted, it will be merged into cFS.

```

**Describe the solution you'd like**
Add links to instructions of "how" to squash a commit using git rebase or how to ammend a commit

**Describe alternatives you've considered**
Leave as is and address with users on a one-on-one, per PR basis

**Comment by skliper** [comment]
Can we do
```
Fix #XYZ, SHORT_DESCRIPTION

LONG_DESCRIPTION (if necessary)
```
and one commit message **per topic**

**Comment by astrogeco** [comment]
We might need to expand on the one commit per topic means. Maybe use some of Joe's PRs as examples?
