### ISSUE TITLE
Create separate app and libraries directories

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFS#247]
**Is your feature request related to a problem? Please describe.**
Having libraries in the apps folder can be confusing especially for beginners.

**Describe the solution you'd like**
New directory called "lib" or "libs" where libraries can "live"

**Describe alternatives you've considered**
Add documentation justifying why it "makes sense" to keep libraries in the apps directory

**Comment by jphickey** [comment]
This already exists, there is a "libs" dir (equivalent to apps) as part of the search path already.  We just don't use it in the bundle.  All we need to do is move e.g. "sample_lib" submodule from `apps` into `libs` in the bundle and it should just work.

**Comment by astrogeco** [comment]
Awesome! I can try that next week
