### ISSUE TITLE
Possible race condition in documentation deploy workflow

### ISSUE THREAD

**Issue by astrogeco** [nasa/cFS#249]
**Describe the bug**
Since the github actions jobs run in parallel there might be a case of two git commits trying to be pushed "at the same time" 

I suggest moving the multiple deploy stages from the separate doc build jobs into a separate deploy job that depends on the successful builds of all docs. Could potentially do something fancy by deploying to separate "local" git branches and then merging them on the deploy branch. 

**To Reproduce**
See https://github.com/nasa/cFS/pull/248/checks?check_run_id=2406018793

**Expected behavior**
All documentation can be deployed 

**Additional context**

**Reporter Info**
Full name and company/organization if applicable

**Comment by skliper** [comment]
Note #234 made it such that the action wasn't running twice, but there are still two deploys from within the document action.  As suggested above, moving the deployment from the two jobs into a deployment job at the end should solve.
