### ISSUE TITLE
Link to join mailing list is broken

### ISSUE THREAD

**Issue by ejtimmon** [nasa/cFS#257]
**Checklist (Please check before submitting)**

* [X ] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [ X] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
The link in the readme file to join the community mailing list results in a "Page Not Found" error.  

**Reporter Info**
Beth Timmons/NASA GSFC

**Comment by astrogeco** [comment]
Current Workaround: 


> send an email to the list <cfs-community@lists.nasa.gov> with the word *subscribe* in the subject line. It will get flagged for moderation and we can then manually add the sender to the list. 

The official method of joining the list seems to be broken right now....
