### ISSUE TITLE
Automate a deployment of docs to GitHub pages

### ISSUE THREAD

**Issue by BaldBeacon** [nasa/cFS#28]
Having to build and open the documentation locally adds an extra step that could be mitigated by pushing the documentation of the current master commit to GitHub pages.

The process of uploading to GitHub pages is documented [here](https://pages.github.com/)

**Comment by skliper** [comment]
Related to https://github.com/nasa/cFE/issues/560

From Circle CI instructions at https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/.  Travis CI is likely similar.

Certainly a useful way to keep our doxygen documentation up to date.  Need to trade approaches.

**Comment by skliper** [comment]
Travis guide: https://docs.travis-ci.com/user/deployment/pages/
