### ISSUE TITLE
Improve Travis CI testing

### ISSUE THREAD

**Issue by skliper** [nasa/cFS#39]
**Is your feature request related to a problem? Please describe.**
Travis CI currently just does cppcheck and default build on the bundle

**Describe the solution you'd like**
Parallel test the following:
- BUILDTYPE=release OMIT_DEPRECATED=true STRICT_NO_WARNINGS=true
- BUILDTYPE=release OMIT_DEPRECATED=false(default) STRICT_NO_WARNINGS=true
- BUILDTYPE=debug(default) OMIT_DEPRECATED=true STRICT_NO_WARNINGS=true
- BUILDTYPE=debug(default) OMIT_DEPRECATED=false(default) STRICT_NO_WARNINGS=true

And do the following tests:
- Add document generation (eventually enforce no warnings)
  - make doc
  - make usersguide
  - make osalguide (dependent on https://github.com/nasa/cFE/pull/446)
- Build with ENABLE_UNIT_TESTS=TRUE SIMULATION=native
- Run unit tests (eventually enforce coverage)
- Execute cFE and pipe output to file
- Send reset cmd from cmdutil
- Confirm execution output lacks error/warning/fail messages

**Describe alternatives you've considered**
None

**Additional context**
Eventually add nightly or triggered local builds for other environments (pc-RTEMS, vxworks on a modern platform)
Eventually add automated build verification (trade CI vs local)

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
Recommend that this be accomplished by using alternate `sample_defs` directories (under different names. of course) for the alternate configs.  This should also ideally cover different CFE config options (e.g. TIME server/client) as some TIME options were broken in the past and failed to compile with these options turned on.

This allows the baseline config which is suggested as a starting point for new users to remain simple and straightforward while allowing the CI config(s) to be as complex as it needs to be to cover all these various options.
