### ISSUE TITLE
Examples for application testing

### ISSUE THREAD

**Issue by BaldBeacon** [nasa/cFS#4]
Since the release of cFE 6.6, there hasn't been apps that give an example of the way tests should be defined in the CMakeLists file. Previously, when UTAssert was part of the tools directory rather than being part of the OSAL, this definition would exist inside of the fsw/for_build/Makefile but this doesn't cleanly translate to cFE 6.6's cmake build system.

The arch_build.cmake file located in the cmake directory seems to have a function [add_unit_test_exe](https://github.com/nasa/cFE/blob/99038d5446aec902e8cdbe14d762a86ea4e19e1c/cmake/arch_build.cmake#L202) but I couldn't get this to work when calling it from the simple app's CMakeList.txt. An explanation of what needs to be done in either the target.cmake or CMakeLists file for an app or an example of an app using UT for it's testing would be appreciated.

**Comment by ejtimmon** [comment]
Yes, this is a problem.  I'm working on getting the GSFC cFS apps fully migrated to cFE 6.6/Cmake.  Hopefully I will have an example to release soon.

**Comment by BaldBeacon** [comment]
Cool, thanks for the confirmation.

**Comment by skliper** [comment]
CCB 20191001 - Plan to incorporate in sample_app and app developer's guide also

**Comment by skliper** [comment]
See https://github.com/nasa/sample_app/pull/26 and https://github.com/nasa/sample_lib/pull/11 as a work in progress.

**Comment by BaldBeacon** [comment]
What was the duplicate issue #?

**Comment by skliper** [comment]
https://github.com/nasa/sample_lib/issues/9 and https://github.com/nasa/sample_app/issues/8, both linked to the pull requests.
