### ISSUE TITLE
Force remove directory in codeql-reusable.yml

### ISSUE THREAD

**Issue by havencarlson** [nasa/cFS#487]
**Checklist (Please check before submitting)**

* [X] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [X] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
In codeql-reusable.yml, it should force remove a directory on line 97 so the script can continue if the directory doesn't exist.

**To Reproduce**
1. Push to branch to run CodeQL
2. Observe failed run if directory didn't exist

**Expected behavior**
If a directory doesn't exist before removing it, the script should continue

**Code snips**
`rm -r ${{ inputs.component-path }}` should be `rm -rf ${{ inputs.component-path }}`
[codeql-reusable.yml](https://github.com/nasa/cFS/blob/main/.github/workflows/codeql-reusable.yml#L97)

**System observed on:**
Browser

**Additional context**
None

**Reporter Info**
Full name and company/organization if applicable

**Comment by skliper** [comment]
Should this be marked as ready for review?
