### ISSUE TITLE
Add lcov to archive results in unit-test-coverage.yml

### ISSUE THREAD

**Issue by chillfig** [nasa/cFS#511]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
The lcov - code coverage report - coverage_total.info is missing from the archived results. Add coverage_total.info to https://github.com/nasa/cFS/blob/561b1284d73356c920940af8ef8d077de8024f08/.github/workflows/unit-test-coverage.yml#L111-L119

**Describe the solution you'd like**
The lcov - code coverage report (index.html) is accessible from each github workflow call.

**Describe alternatives you've considered**
Opening the lcov - code coverage report  (the index.html file ) over ssh (https://unix.stackexchange.com/questions/159622/open-file-over-ssh-in-local-x-window).

**Requester Info**
Justin Figueroa, ASRC Federal

**Comment by astrogeco** [comment]
I've also been brainstorming another idea based on this badge <https://github.com/emibcn/badge-action>
