### ISSUE TITLE
Referer to nasa/cFE#2112

### ISSUE THREAD

**Issue by paulober** [nasa/cFS#517]
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

-> Referer to nasa/cFE#2112

**Comment by skliper** [comment]
I assume this was submitted in err, see #516, feel free to reopen if needed.
