### ISSUE TITLE
Automate generation of CCB Agenda

### ISSUE THREAD

**Issue by ArielSAdams** [nasa/cFS#566]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
Reduce time spent on manually creating CCB Agenda. 

**Describe the solution you'd like**
Create a new workflow that uses the workflow_dispatch event. The workflow should identify PRs and their issues that have the label CCB Ready. The document should list the author, PR title, link to PR, and the PR linked issue title. This file should be uploaded to the Wiki. 

**Describe alternatives you've considered**
Keep as is. 

**Additional context**
Will most likely need to create new action.
Possible actions that may be used: 
1. https://github.com/marketplace/actions/list-pull-requests
- Outputs PR title and link based on label. Doesn't work across multiple repos. 
2. https://github.com/budziq/pulls_since
- Outputs PR author, PR title, and link. Works for any repo/multiple repos. Doesn't pull based on labels. 
3. https://github.com/sshaw/export-pull-requests
- Outputs PR author, PR title, PR link, and issue based on label. Creates CSV file. Needs to convert to a markdown file for Wiki repo. 

Github repo wiki is actually a repo with named reponame.wiki. 

**Requester Info**
Ariel Adams, MCSG Tech.

**Comment by skliper** [comment]
I recommend considering adding every PR that doesn't have the CCB:Ignore label, or come up with a process to assign PR's without the CCB:Ready/Ignore labels to cFS team members to review and promote to CCB:Ready... otherwise community PR's get neglected and/or PR's stagnate.  Note the CCB:Ignore label should be accompanied by a comment as to what the path forward is.

**Comment by skliper** [comment]
Note you could also probably automate via one of the GitHub CLI's, either hub or gh could likely generate the list across all repos w/ a fairly simple script.

**Comment by skliper** [comment]
List of all non CCB:Ignore PRs (over all repos) sorted by user:
```
(repolist="CF CS DS FM HK HS LC MD MM SC cFE osal PSP sample_app sample_lib ci_lab to_lab sch_lab cFS-GroundSystem elf2cfetbl tblCRCTool"; for repo in $repolist; do   gh api --method GET -H "Accept: application/vnd.github.v3+json" /repos/nasa/$repo/pulls --jq '.[] | select(any(.labels[].name ; contains("CCB:Ignore")) | not) | "\(.user.login): \(.url) \(.title)"'; done) | sort
```
