### ISSUE TITLE
Reference autogenerated docs

### ISSUE THREAD

**Issue by skliper** [nasa/cFS#63]
**Is your feature request related to a problem? Please describe.**
See #61 
No current references to the generated documents

**Describe the solution you'd like**
Once the docs are deployed the first time (after push of #61 to master and CI completes) add references from at least README.md.

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by skliper** [comment]
Just add references in README.md to the documents in the gh_pages branch.

**Comment by JandlynBentley-at-NASA** [comment]
I'm looking for clarification (I'm new to cFS).  Which references are you specifically referring to?

**Comment by skliper** [comment]
https://github.com/nasa/cFS/tree/gh-pages

**Comment by JandlynBentley-at-NASA** [comment]
Apologies for not being more specific, I meant which references in the README should be added to the cFE and OSAL user guides in the gh pages branch?

**Comment by skliper** [comment]
I may not be understanding the question, but the request is to add references in the README.md to the user's guides.  Just add a "References to auto-generated documentation" section, and links to the two files.
