### ISSUE TITLE
Add reference to skeleton_app in README

### ISSUE THREAD

**Issue by skliper** [nasa/cFS#68]
**Is your feature request related to a problem? Please describe.**
Skeleton app added, missing reference in readme

**Describe the solution you'd like**
Add reference

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by JandlynBentley-at-NASA** [comment]
Looking for clarification (I'm new to cFS). What is the "Skeleton app"? I don't see anything labeled that in the cFS bundle code.

**Comment by skliper** [comment]
> Looking for clarification (I'm new to cFS). What is the "Skeleton app"? I don't see anything labeled that in the cFS bundle code.

https://github.com/nasa/skeleton_app
