### ISSUE TITLE
Header Guards for C++ applications to call CFE, OSAL, PSP

### ISSUE THREAD

**Issue by irowebbn** [nasa/cFS#688]
**Checklist (Please check before submitting)**

* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Describe the solution you'd like**
Wrap all public headers in CFE, OSAL, and PSP in hedaer guards that allow inclusion from C++ translation units:
```c
#ifdef __cplusplus
extern "C" {
#endif

<content>

#ifdef __cplusplus
}
#endif
```

**Describe alternatives you've considered**
The alternative is to wrap the `#includes` in the calling apps with the header guards. 

**Additional context**
- https://lists.nasa.gov/archives/list/cfs-community@lists.nasa.gov/thread/HMXU7ORGRU5ZWPAXIBNCI2MEDL5WL6RW/
- https://github.com/nasa/cFS/discussions/659
- https://lists.nasa.gov/archives/list/cfs-community@lists.nasa.gov/thread/OANSPI46GVMPNNNSB467P5LD23F274GO/
- https://lists.nasa.gov/archives/list/cfs-community@lists.nasa.gov/thread/3BRMUGGE2TOLGKIP6NIQNZV4UWTJIUAF/

**Requester Info**
Isaac Rowe, NASA JSC, Jacobs Technology

**Comment by dzbaker** [comment]
CCB 21 November 2024: Closing as we don't test C++ support.
