### ISSUE TITLE
use appid instead of perfid?

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/cFS#7]
Currently apps define their perfid when using the performance logging framework, but there's no mechanism currently to ensure that the perfid is unique to that application and could result in confused perf logs.

One option would be to use the appid generated when the application is registered (but will need to be reported somehow so that a performance analysis tool can crosswalk from runtime-generated perfid's to the applications.)

**Comment by skliper** [comment]
@CDKnightNASA could you re-submit as a feature request per the template?
