### ISSUE TITLE
cFS start guide

### ISSUE THREAD

**Issue by Gonta01** [nasa/cFS#771]
[CFS-101 TRAINING GUIDE](https://software.nasa.gov/software/MSC-26323-1) is significantly deprecated. Are there any fresh guides on how to work with current version of cFS?
What documentation can be handy?

**Comment by dzbaker** [comment]
Most up-to-date training can be found here: https://ntrs.nasa.gov/api/citations/20240000217/downloads/cFS_Training_Draco.pptx. Closing issue (please follow up in Discussions if there are more questions).
