### ISSUE TITLE
consider using "REUSE" for license/copyright banner management

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/cFS#82]
Currently copyright headers and the like are all over the map, this software would help automatically check that all of our copyright and license information is correct in every file in the cFS tree.

See: https://reuse.software/

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by skliper** [comment]
I like it, but would require our OPC to accept the SPDX standard.

**Comment by skliper** [comment]
Status update - request OPC review of the SPDX standard, pending response
