### ISSUE TITLE
Reintroduce gen_app_code tool

### ISSUE THREAD

**Issue by NickHauptvogel** [nasa/cFS#9]
Hi,

I cannot find the gen_app_code tool, although it is mentioned in the official CFS-101. How can I effectively create an app now?

Regards,
Nick

**Comment by skliper** [comment]
The gen_app_code tool and CFS-101 repo are outside the scope of the cFS Framework, and are supported, maintained, and released by a different center.  You may have better luck posting an issue on the CFS-101 repo if you require access to the gen_app_code tool.

The resources the cFS Framework does provide for app development include the cFE Application Developers Guild (located in the docs directory of http://github.com/nasa/cFE, included in this repo as a submodule) and the sample app at https://github.com/nasa/sample_app (also included in this repo as a submodule) as an example.
