### ISSUE TITLE
Update lgtm.yml to exclude Ui files

### ISSUE THREAD

**Issue by lbleier-GSFC** [nasa/cFS#92]
**Describe the bug**
The auto-generated `.py` files created by `pyuic5` should not be analyzed by lgtm

**Expected behavior**
Do not have lgtm analysis include files starting with `Ui_`

**Additional context**
This is specifically related to nasa/cFS-GroundSystem#46

**Reporter Info**
Leor Bleier, NASA GSFC\Code 582

**Comment by skliper** [comment]
Wasn't actually solved by commits above.

**Comment by lbleier-GSFC** [comment]
> Wasn't actually solved by commits above (#94 didn't work).

I admit I don't fully understand how lgtm works with this file. The exclude line I added might simply be in the wrong place.
