### ISSUE TITLE
Boolean Type Not Defined ?

### ISSUE THREAD

**Issue by PaulaBosca** [nasa/cFS#98]
I'm new to cFS and trying to slowly add the applications I will need for my mission. I'm trying to add the TO, SCH, and HK apps but keep running into the same problem. It appears that in many app codes such as sch_msg.h, sch_app.h, etc. there is use of 'boolean'. It doesn't appear that the boolean type has been defined anywhere in the cFS code. Am I missing something or does it have to be manually added in? 

****System observed on:**
 - VM running Ubuntu 18.04.4 64bit
 - Versions running all the current versions of cfs bundle, cfs apps, and cfe/osal/psp

Paula

**Comment by skliper** [comment]
Note we did convert the framework to just use bool/true/false (vs custom defined boolean/TRUE/FALSE).

**Comment by PaulaBosca** [comment]
The framework works if it's built OMIT_DEPRECATED=false. If the OMIT_DEPRECATED=true is included, then the build fails. A simple fix for this is including the boolean and true/false definitions in the common_types header outside of the OMIT_DEPRECATED portion. 
My build still failed, but for other reasons I'm working out

**Comment by jphickey** [comment]
> The framework works if it's built OMIT_DEPRECATED=false. If the OMIT_DEPRECATED=true is included, then the build fails

Can you clarify what fails?  Is it in the CFE core framework or an external app?

The intent is to get away from the custom boolean/TRUE/FALSE and just use the C99 standard types/symbols for boolean data.  The core framework should be fully compliant in this regard but 3rd party apps may not be.  

The option of setting `OMIT_DEPRECATED=true` is more of a test to build against what a future version of CFE will be once all the deprecated elements are fully removed.  If you just build with default settings, the deprecated items are still included, which is the intent.  Users are certainly welcome to test with the setting at `true` and file a bug report for anything that breaks with the respective app developer/vendor, but that's mainly to check compatibility with the _next_ version, not the current version.

So - in short - if building with `OMIT_DEPRECATED=false` (or not specifying this at all, the default) works then you are fine - just build that way.

**Comment by PaulaBosca** [comment]
Thanks so much for the response! I'll just build with the omit_deprecated=false from now on. Thanks for all your help!

**Comment by igor10091972** [comment]
Paola, please tell me where the OMIT_DEPRECATED = false flag should be set? Otherwise, I also can't build a system with the SCH scheduler .... (

**Comment by skliper** [comment]
Note OMIT_DEPRECATED is "false" by default.  You only need to provide the flag (at the prep stage) if you want to set it as true.  Probably also worth noting the Caelum development cycle removed the deprecated support that was last available in the Bootes release candidates.

**Comment by DBprod** [comment]
Hello, I recently pulled cFS from main, I followed the steps found here (https://ntrs.nasa.gov/api/citations/20205000691/downloads/TM%2020205000691.pdf) on page 191 but receive the same issues mentioned in this post. The steps I followed are:

Part 1- Integrate the Scheduler application
1. Clone the Scheduler application
```
cd cFS/apps
git clone https://github.com/nasa/SCH.git sch
cd sch
git checkout rc-2.2.2
git pull
```
2. Replace "sch_lab" with "sch" in the sample_defs/targets.cmake file (line 88)
3. Update the cFE startup script (sample_defs/cpu1_cfe_es_startup.scr) by replacing sch_lab entry with:
CFE_APP,   sch , SCH_AppMain, SCH, 90, 16384, 0x0, 0;

4. Update SCH table paths. In the apps/sch/fsw/platform_inc/sch_platform_cfg.h
file, change the following #defines to the values shown below.
#define SCH_SCHEDULE_FILENAME "/cf/sch_def_schtbl.tbl"
#define SCH_MESSAGE_FILENAME "/cf/sch_def_msgtbl.tbl"
5. Build the cFS
make clean
make prep
make
make install
5. Run the cFE
cd build/exe/cpu1
./core-cpu1

However, after step 5 I run into the same issues. I tried to do make OMIT_DEPRECATED=true prep but the result was unchanged. Is there a newer version of SCH I could obtain to avoid these issues or a workaround to this?  Thank you

**Comment by skliper** [comment]
There is an unreleased/internal version of SCH that I think has been updated to be compliant with Draco, but I'm not aware of the release plan.  Maybe @astrogeco or @ejtimmon know?
